import type {NextConfig} from 'next';

const nextConfig: NextConfig = {
  /* config options here */
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'picsum.photos',
        port: '',
        pathname: '/**',
      },
       {
         // Allow images generated by Genkit/Google AI
         protocol: 'https',
         hostname: 'lh3.googleusercontent.com',
         port: '',
         pathname: '/**',
       },
       {
         // Allow YouTube thumbnails (example pattern, might need adjustment based on actual thumbnail URLs)
         protocol: 'https',
         hostname: 'i.ytimg.com',
         port: '',
         pathname: '/vi/**',
       },
       {
         // Allow Firebase Storage images (if used)
          protocol: 'https',
          hostname: 'firebasestorage.googleapis.com',
          port: '',
          pathname: '/v0/b/**',
       }
    ],
     // Allow data URIs for generated images
     dangerouslyAllowSVG: true,
     contentDispositionType: 'attachment',
     contentSecurityPolicy: "default-src 'self'; script-src 'none'; sandbox;",
     // Enable handling of data URIs
     // This might not be needed explicitly depending on Next.js version,
     // but `unoptimized={true}` on the Image component is the primary way to handle data URIs.
     // domains: ['data:'], // This syntax is often incorrect. Use remotePatterns for hosts.
  },
};

export default nextConfig;